version: '3'
services:
  soaper:
    build: .
    container_name: soaper
    volumes: 
        - './mousseurs.db:/usr/src/app/mousseurs.db'
    environment: 
        - 'TZ=Europe/Paris'
    restart: unless-stopped